"use client";
import { useState } from "react";
import Link from "next/link";
import "./join.css";

export default function JoinPage() {
  const [done, setDone] = useState(false);
  return <main><nav className="nav"><Link className="brand" href="/"><span className="brand-mark">DG</span><span>DoingGood <b>Youth Connect</b></span></Link><Link className="text-link" href="/">← Back to DYC</Link></nav><section className="join-page pattern"><div className="join-panel">{done ? <><p className="eyebrow blue">Welcome to DYC</p><h1>You’re connected.</h1><p>Your preferences have been recorded for this prototype. In the full platform, you will receive only the updates you select.</p><Link className="button primary" href="/">Explore DYC <span>→</span></Link></> : <><p className="eyebrow blue">Voluntary participation</p><h1>Join a community that listens.</h1><p className="join-intro">DoingGood Youth Connect is a politically affiliated civic engagement and youth development initiative, separate from SAIL.</p><form onSubmit={(e)=>{e.preventDefault();setDone(true)}}><label>First name<input required placeholder="Your first name" /></label><label>Email or phone<input required placeholder="you@example.com" /></label><label className="check"><input type="checkbox" required /> I confirm that I am aged 18–35.</label><label className="check"><input type="checkbox" required /> I understand that joining is voluntary and does not affect access to independent programmes or benefits.</label><fieldset><legend>Choose your updates</legend><label className="check"><input type="checkbox" defaultChecked /> Civic knowledge and stewardship reports</label><label className="check"><input type="checkbox" defaultChecked /> Youth opportunities, volunteering, and mentorship</label><label className="check"><input type="checkbox" /> Political or party-related communications</label></fieldset><button className="button primary" type="submit">Continue to DYC <span>→</span></button><small>By continuing, you agree to review the Privacy Notice and can withdraw any choice later.</small></form></>}</div></section><footer><span className="brand-mark">DG</span><span>DoingGood Youth Connect</span><span className="footer-note">An initiative of Senator Tokunbo Abiru · Separate from SAIL</span></footer></main>;
}
